
spring:
  datasource:
    url: jdbc:sqlserver://restapicourse.database.windows.net:1433;database=course-file;user=restapi@Akash9696@;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: restapi 
    password:Akash9696@
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernet.dialect.SQLServer2012Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
      
     
server:
 port: 8055
